logo: Sehwan# add logo name
title: Sehwan
description: Sehwan 기술블로그
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author-pic:  face.jpg# your photo
author-name: KIM-SEHWAN
about-author: Hello.
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # you website

# Disqus
discus_identifier: mr-brown

# Newsletter
mailchimp: 


# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: 

encoding: UTF-8

